<#
.SYNOPSIS
    General-purpose finder for failed logon attempts on a Windows server (Security log 4625,
    optionally Kerberos failures from a DC 4768/4769/4771, and IIS 401/403 errors if IIS is installed).
    For every record it prints: the raw diagnostic fields pulled from the log (Evidence), the
    unmodified native message text as generated by Windows/IIS (NativeMessage), a plain-language
    translation of the failure code (Reason), a rough category (Category), and a suggested next
    diagnostic step (Guidance).

.DESCRIPTION
    Not tied to any specific system or investigation - works on any Windows server with a
    Security log (and optionally IIS). Must run as Administrator, otherwise the Security log
    silently returns "No events found" even when matching events exist.

    IMPORTANT: Reason, Category and Guidance are this script's own interpretation of the raw
    code, not verbatim text from the log. NativeMessage is the actual text Windows/IIS produced,
    unmodified, so you always have the original to fall back on or compare against.

.PARAMETER MinutesBack
    How far back in time to search. Default 120 minutes.

.PARAMETER SiteName
    IIS website to read logs from (if IIS is installed). Default "Default Web Site".
    Ignored when -SkipIis is used.

.PARAMETER IpFilter
    Optional - restrict results to a specific IP address or list of IP addresses.

.PARAMETER UserFilter
    Optional - restrict results to specific username(s) (SamAccountName, no domain, exact match).

.PARAMETER DomainController
    Optional - name of a DC to pull Kerberos failures from (Event ID 4768/4769/4771). These are
    logged on the DC, not on the target server, and often give a more precise reason for
    Kerberos/SPN problems than 4625 alone. Requires permission to read the Security log on that DC.

.PARAMETER SkipIis
    Skips reading IIS logs entirely (e.g. if the server has no IIS, or you only care about
    OS-level logon failures).

.PARAMETER ExportCsv
    Also saves the combined result to a CSV file.

.PARAMETER CsvPath
    Path to the CSV file used when -ExportCsv is set.
    Default: ".\FailedLogons_<timestamp>.csv"

.EXAMPLE
    .\Get-FailedLogons.ps1 -MinutesBack 60 -IpFilter "172.16.100.22"
    Looks back 60 minutes for failed logons from a single client IP, across the
    Security log and IIS logs.

.EXAMPLE
    .\Get-FailedLogons.ps1 -UserFilter "jo2999" -DomainController DC01 -ExportCsv
    Looks for failures for a specific user, also pulling Kerberos failures from DC01,
    and exports the combined result to a timestamped CSV file.

.EXAMPLE
    .\Get-FailedLogons.ps1 -SkipIis -MinutesBack 1440
    Looks back 24 hours (1440 minutes), skipping IIS logs entirely - Security log only.

.NOTES
    Version: 1.0 (2026-08-20)
    Author:  Richard Hlavienka (richard.hlavienka@elyvyn.com)
#>

[CmdletBinding()]
param(
    [int]$MinutesBack = 120,
    [string]$SiteName = "Default Web Site",
    [string[]]$IpFilter,
    [string[]]$UserFilter,
    [string]$DomainController,
    [switch]$SkipIis,
    [switch]$ExportCsv,
    [string]$CsvPath = ".\FailedLogons_$(Get-Date -Format 'yyyyMMdd_HHmmss').csv"
)

# --- Elevation check ---
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    throw "This script must run as Administrator, otherwise the Security log is not readable."
}

# ============================================================================
# KNOWN CODE MAP: Code -> Reason (plain-language translation) / Category (bucket
# for grouping/filtering) / Guidance (suggested next diagnostic step).
# Not exhaustive - an unrecognized code is always printed raw, never silently dropped.
# ============================================================================
$knownCodes = @(
    # --- NTSTATUS codes (Event 4625, both Status and SubStatus fields) ---
    @{ Code='0xC0000064'; Reason='The specified user account does not exist';               Category='UnknownUser';       Guidance='Verify the username is correct and that the account exists in AD (Get-ADUser).' }
    @{ Code='0xC000006A'; Reason='Incorrect password (username is correct)';                Category='BadPassword';       Guidance='Confirm the password with the user. If this repeats, check the Account Lockout Policy and any cached credentials on the client.' }
    @{ Code='0xC000006D'; Reason='Generic authentication failure - bad username or password'; Category='BadPassword';     Guidance='Check both the Status and SubStatus fields separately - this code is often just a wrapper; the real reason may be in the other field.' }
    @{ Code='0xC0000234'; Reason='Account is locked out';                                   Category='AccountLockedOut';  Guidance='Check Get-ADUser -Properties LockedOut,BadPwdCount; identify the source of repeated bad attempts (multiple devices/apps with an old cached password).' }
    @{ Code='0xC0000072'; Reason='Account is disabled';                                     Category='AccountDisabled';   Guidance='Check Get-ADUser -Properties Enabled; re-enable if it should be active.' }
    @{ Code='0xC0000193'; Reason='Account has expired (account expiration)';                Category='AccountExpired';    Guidance='Check Get-ADUser -Properties AccountExpirationDate.' }
    @{ Code='0xC0000071'; Reason='Password has expired';                                    Category='PasswordExpired';   Guidance='The user needs to change their password (e.g. via OWA, or Ctrl+Alt+Del on a domain-joined workstation).' }
    @{ Code='0xC0000224'; Reason='User must change password at next logon';                 Category='PasswordExpired';   Guidance='Forced password change - clients without a GUI (e.g. IMAP/EWS) cannot handle the change prompt and will keep failing.' }
    @{ Code='0xC000006F'; Reason='Logon outside allowed hours (logon hours restriction)';   Category='TimeRestriction';   Guidance='Check Logon Hours on the account in AD Users and Computers.' }
    @{ Code='0xC0000070'; Reason='Logon from this workstation is not permitted (workstation restriction)'; Category='WorkstationRestriction'; Guidance='Check the logonWorkstations attribute on the account in AD.' }
    @{ Code='0xC000015B'; Reason='The account does not have the requested logon type (user right) on this computer'; Category='LogonRightDenied'; Guidance='Check Local/Group Policy -> User Rights Assignment (Access this computer from the network / Allow log on locally / Deny...) on the target server via gpresult /h or secpol.msc. Also check the user''s nested group membership (Get-ADGroupMember -Recursive) against any Deny list.' }
    @{ Code='0xC0000133'; Reason='Clock skew between client and DC is too large (Kerberos tolerance ~5 min)'; Category='ClockSkew'; Guidance='Compare client and DC time (w32tm /stripchart), fix NTP sync.' }
    @{ Code='0xC0000371'; Reason='Problem with the account''s secret key (Kerberos, may relate to SPN/trust)'; Category='SpnOrTrustIssue'; Guidance='Check for duplicate/missing SPNs (setspn -X, setspn -Q), and inter-domain trust if relevant.' }
    @{ Code='0xC0000225'; Reason='Internal inconsistency - may indicate a DC/replication problem'; Category='DcInconsistency'; Guidance='Check AD replication health (repadmin /replsummary) and DC health (dcdiag).' }
    @{ Code='0xC0000413'; Reason='Logon blocked by an Authentication Policy Silo';           Category='AuthPolicySilo';    Guidance='Check Get-ADAuthenticationPolicySilo and the user''s silo assignment.' }

    # --- Kerberos codes (Event 4768/4769/4771, Status/ResultCode field, short hex without leading zeros) ---
    @{ Code='0x6';  Reason='Unknown client (KDC_ERR_C_PRINCIPAL_UNKNOWN)';                  Category='UnknownUser';       Guidance='The account likely does not exist or was renamed/deleted.' }
    @{ Code='0x7';  Reason='Unknown server / SPN problem (KDC_ERR_S_PRINCIPAL_UNKNOWN)';    Category='SpnOrTrustIssue';   Guidance='Common with a missing or duplicate SPN - check setspn -L <account> and setspn -X for duplicates.' }
    @{ Code='0x12'; Reason='Account disabled, expired, or locked (KDC_ERR_CLIENT_REVOKED)'; Category='AccountDisabled';   Guidance='Check Enabled/LockedOut/AccountExpirationDate on the account.' }
    @{ Code='0x17'; Reason='Password has expired (KDC_ERR_KEY_EXPIRED)';                    Category='PasswordExpired';   Guidance='The user needs to change their password.' }
    @{ Code='0x18'; Reason='Incorrect pre-authentication data - bad password (KDC_ERR_PREAUTH_FAILED)'; Category='BadPassword'; Guidance='Confirm the password with the user; also common with an old cached password in an app or mobile device.' }
    @{ Code='0x1F'; Reason='Integrity check failed (possible shared-key problem)';           Category='SpnOrTrustIssue';   Guidance='Check the inter-domain/forest trust and credential synchronization.' }
    @{ Code='0x20'; Reason='Ticket has expired';                                            Category='TicketExpired';     Guidance='The client needs a new ticket - also verify time sync.' }
    @{ Code='0x21'; Reason='Ticket not yet valid (clock skew)';                             Category='ClockSkew';         Guidance='Check the client''s time sync against the DC.' }
    @{ Code='0x25'; Reason='Clock skew between client and KDC too large';                   Category='ClockSkew';         Guidance='Check the client''s time sync against the DC (w32tm).' }
    @{ Code='0x26'; Reason='Replay detected (repeated request)';                            Category='ReplayDetected';    Guidance='Usually a consequence of clock skew or NAT issues - check time and the client''s network path.' }
)

# IIS sub-status codes (401.x / 403.x) - separate map, format is decimal, not hex
$iisCodes = @(
    @{ Code='401.1'; Reason='Logon failed - invalid credentials';                           Category='BadPassword';           Guidance='Verify the client is sending correct credentials; also check the Security log on this server for a more precise reason (Event 4625).' }
    @{ Code='401.2'; Reason='Logon failed due to server configuration - authentication method not enabled on the server'; Category='AuthMethodNotEnabled'; Guidance='Check the IIS Authentication settings on the relevant virtual directory/site (e.g. Get-WebConfiguration windowsAuthentication).' }
    @{ Code='401.3'; Reason='Unauthorized due to ACL on the target resource';                Category='AclDenied';              Guidance='Check the NTFS permissions on the target file/directory for this user.' }
    @{ Code='401.5'; Reason='Authorization denied by ISAPI/CGI application';                 Category='AppLevelDenied';         Guidance='Check the logs/configuration of the relevant ISAPI/CGI application.' }
    @{ Code='403.1'; Reason='Forbidden - execute access forbidden';                          Category='Forbidden';              Guidance='Check Execute permissions on this directory in IIS.' }
    @{ Code='403.4'; Reason='SSL required';                                                  Category='SslRequired';            Guidance='The client is connecting over HTTP instead of HTTPS.' }
    @{ Code='403.7'; Reason='Client certificate required';                                   Category='ClientCertRequired';     Guidance='Check whether the client has a properly installed and mapped client certificate.' }
)

# LogonType translation (informational only, not itself a failure reason)
$logonTypeMap = @{
    '2'  = 'Interactive'; '3'  = 'Network'; '4'  = 'Batch'; '5'  = 'Service'; '7'  = 'Unlock'
    '8'  = 'NetworkCleartext'; '9'  = 'NewCredentials'; '10' = 'RemoteInteractive'; '11' = 'CachedInteractive'
}

function Resolve-KnownCode {
    param([string]$Code, [array]$Table)
    $match = $Table | Where-Object { $_.Code -eq $Code }
    if ($match) { return $match }
    return @{ Code = $Code; Reason = "Unrecognized code: $Code (not in this script's internal map - look it up in the NTSTATUS/Kerberos/HTTP documentation)"; Category = 'Unknown'; Guidance = 'This code is not recognized by the script - verify it manually against the NTSTATUS/Kerberos error code reference.' }
}

function Get-FailedLogonEvents {
    param([int]$MinutesBack, [string[]]$IpFilter, [string[]]$UserFilter)

    $start = (Get-Date).AddMinutes(-$MinutesBack)
    try {
        $events = Get-WinEvent -FilterHashtable @{LogName='Security'; Id=4625; StartTime=$start} -ErrorAction Stop
    }
    catch {
        Write-Warning "Nothing in the Security log for the last $MinutesBack minutes (Id 4625)."
        return @()
    }

    $events | ForEach-Object {
        $xml    = [xml]$_.ToXml()
        $data   = $xml.Event.EventData.Data
        $status = ($data | Where-Object Name -eq 'Status').'#text'
        $sub    = ($data | Where-Object Name -eq 'SubStatus').'#text'
        $ip     = ($data | Where-Object Name -eq 'IpAddress').'#text'
        $port   = ($data | Where-Object Name -eq 'IpPort').'#text'
        $user   = ($data | Where-Object Name -eq 'TargetUserName').'#text'
        $domain = ($data | Where-Object Name -eq 'TargetDomainName').'#text'
        $logonT = ($data | Where-Object Name -eq 'LogonType').'#text'
        $auth   = ($data | Where-Object Name -eq 'AuthenticationPackageName').'#text'
        $wstat  = ($data | Where-Object Name -eq 'WorkstationName').'#text'
        $lproc  = ($data | Where-Object Name -eq 'LogonProcessName').'#text'

        # For NTLM the real reason tends to sit in Status, with SubStatus left at 0x0.
        # For Kerberos it's the reverse. Take the first code that isn't 0x0.
        $effectiveCode = if ($sub -and $sub -ne '0x0') { $sub }
                          elseif ($status -and $status -ne '0x0') { $status }
                          else { $sub }

        $resolved = Resolve-KnownCode -Code $effectiveCode -Table $knownCodes
        $logonLabel = if ($logonT -and $logonTypeMap.ContainsKey($logonT)) { "$logonT ($($logonTypeMap[$logonT]))" } else { $logonT }

        $nativeMessage = if ($_.Message) { $_.Message } else { '(native message unavailable - message resource DLL not found for this provider on this system)' }

        [PSCustomObject]@{
            Time          = $_.TimeCreated
            Source        = 'SecurityLog (4625)'
            ClientIP      = $ip
            User          = $user
            Domain        = $domain
            RawCode       = $effectiveCode
            Category      = $resolved.Category
            Reason        = $resolved.Reason
            Guidance      = $resolved.Guidance
            Evidence      = "Status=$status SubStatus=$sub LogonType=$logonLabel AuthPackage=$auth Workstation=$wstat LogonProcess=$lproc IpPort=$port"
            NativeMessage = $nativeMessage
        }
    } | Where-Object {
        (-not $IpFilter -or $IpFilter -contains $_.ClientIP) -and
        (-not $UserFilter -or $UserFilter -contains $_.User)
    }
}

function Get-KerberosDcFailures {
    param([string]$DomainController, [int]$MinutesBack, [string[]]$IpFilter, [string[]]$UserFilter)

    if (-not $DomainController) { return @() }
    $start = (Get-Date).AddMinutes(-$MinutesBack)
    try {
        $events = Get-WinEvent -ComputerName $DomainController -FilterHashtable @{LogName='Security'; Id=4768,4769,4771; StartTime=$start} -ErrorAction Stop
    }
    catch {
        Write-Warning "Could not read the Security log from '$DomainController' (permission/availability), or there is nothing there."
        return @()
    }

    $events | ForEach-Object {
        $xml  = [xml]$_.ToXml()
        $data = $xml.Event.EventData.Data
        $code = ($data | Where-Object Name -eq 'Status').'#text'
        if (-not $code) { $code = ($data | Where-Object Name -eq 'ResultCode').'#text' }
        $ip     = ($data | Where-Object Name -eq 'IpAddress').'#text'
        $port   = ($data | Where-Object Name -eq 'IpPort').'#text'
        $user   = ($data | Where-Object Name -eq 'TargetUserName').'#text'
        $domain = ($data | Where-Object Name -eq 'TargetDomainName').'#text'
        $svc    = ($data | Where-Object Name -eq 'ServiceName').'#text'

        # Successful events (0x0) are not of interest here
        if (-not $code -or $code -eq '0x0') { return }

        $resolved = Resolve-KnownCode -Code $code -Table $knownCodes
        $nativeMessage = if ($_.Message) { $_.Message } else { '(native message unavailable - message resource DLL not found for this provider on this system)' }

        [PSCustomObject]@{
            Time          = $_.TimeCreated
            Source        = "KerberosDC (Event $($_.Id))"
            ClientIP      = $ip
            User          = $user
            Domain        = $domain
            RawCode       = $code
            Category      = $resolved.Category
            Reason        = $resolved.Reason
            Guidance      = $resolved.Guidance
            Evidence      = "ResultCode=$code ServiceName=$svc IpPort=$port (recorded on DC $DomainController)"
            NativeMessage = $nativeMessage
        }
    } | Where-Object {
        $_ -and (-not $IpFilter -or $IpFilter -contains $_.ClientIP) -and (-not $UserFilter -or $UserFilter -contains $_.User)
    }
}

function Get-IisAuthFailures {
    param([string]$SiteName, [int]$MinutesBack, [string[]]$IpFilter, [string[]]$UserFilter)

    Import-Module WebAdministration -ErrorAction SilentlyContinue
    $site = Get-Website -Name $SiteName -ErrorAction SilentlyContinue
    if (-not $site) { Write-Warning "IIS site '$SiteName' was not found (or IIS is not installed) - skipping IIS logs."; return @() }

    $logDir  = [System.Environment]::ExpandEnvironmentVariables($site.logFile.directory)
    $logPath = Join-Path $logDir "W3SVC$($site.id)"
    $latest  = Get-ChildItem $logPath -Filter "u_ex*.log" -ErrorAction SilentlyContinue |
               Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $latest) { Write-Warning "No IIS log file found in $logPath."; return @() }

    # The #Fields header is always at the very start of the file - read it separately from
    # Tail (which reads the END of the file), otherwise the header gets missed on large/busy logs.
    $fieldLine = Select-String -Path $latest.FullName -Pattern '^#Fields:' | Select-Object -First 1
    if (-not $fieldLine) { Write-Warning "Could not read the IIS log format (#Fields missing - file may not have a W3C header)."; return @() }
    $fields = ($fieldLine.Line -replace '#Fields:\s*', '') -split '\s+'

    $lines = Get-Content $latest.FullName -Tail 8000
    $threshold = (Get-Date).AddMinutes(-$MinutesBack)

    # Note: IIS logs are often in UTC by default while the Security log uses local server time - account for the offset.
    $lines | Where-Object { $_ -notlike '#*' -and $_.Trim() -ne '' } | ForEach-Object {
        $rawLine = $_
        $vals = $rawLine -split '\s+'
        if ($vals.Count -lt $fields.Count) { return }
        $obj = [ordered]@{}
        for ($i = 0; $i -lt $fields.Count; $i++) { $obj[$fields[$i]] = $vals[$i] }
        $entry = [PSCustomObject]$obj

        [datetime]$entryTime = 0
        if (-not [DateTime]::TryParse("$($entry.date) $($entry.time)", [ref]$entryTime)) { return }
        if ($entryTime -lt $threshold) { return }
        if ($IpFilter -and ($IpFilter -notcontains $entry.'c-ip')) { return }
        if ($UserFilter -and ($UserFilter -notcontains $entry.'cs-username')) { return }
        if ($entry.'sc-status' -notmatch '^(401|403)') { return }

        $key = "$($entry.'sc-status').$($entry.'sc-substatus')"
        $resolved = Resolve-KnownCode -Code $key -Table $iisCodes

        [PSCustomObject]@{
            Time          = $entryTime
            Source        = 'IISLog'
            ClientIP      = $entry.'c-ip'
            User          = $entry.'cs-username'
            Domain        = $null
            RawCode       = $key
            Category      = $resolved.Category
            Reason        = $resolved.Reason
            Guidance      = $resolved.Guidance
            Evidence      = "HTTP $($entry.'sc-status').$($entry.'sc-substatus') Win32=$($entry.'sc-win32-status') $($entry.'cs-method') $($entry.'cs-uri-stem') UA=$($entry.'cs(User-Agent)')"
            NativeMessage = "(raw IIS log line - not a Windows event message): $rawLine"
        }
    }
}

# --- Main ---
Write-Host "Reading Security log (Id 4625, last $MinutesBack min)..." -ForegroundColor Cyan
$secFailures = Get-FailedLogonEvents -MinutesBack $MinutesBack -IpFilter $IpFilter -UserFilter $UserFilter

$iisFailures = @()
if (-not $SkipIis) {
    Write-Host "Reading IIS logs (401/403, last $MinutesBack min)..." -ForegroundColor Cyan
    $iisFailures = Get-IisAuthFailures -SiteName $SiteName -MinutesBack $MinutesBack -IpFilter $IpFilter -UserFilter $UserFilter
}

$kerbFailures = @()
if ($DomainController) {
    Write-Host "Reading Kerberos failures from DC '$DomainController' (4768/4769/4771)..." -ForegroundColor Cyan
    $kerbFailures = Get-KerberosDcFailures -DomainController $DomainController -MinutesBack $MinutesBack -IpFilter $IpFilter -UserFilter $UserFilter
}

$all = @($secFailures) + @($iisFailures) + @($kerbFailures) | Sort-Object Time -Descending

if (-not $all -or $all.Count -eq 0) {
    Write-Host "`nNo failed logons found in the last $MinutesBack minutes." -ForegroundColor Green
}
else {
    Write-Host "`nRecords found: $($all.Count)" -ForegroundColor Yellow
    Write-Host "--- Overview ---" -ForegroundColor Cyan
    $all | Select-Object Time, Source, ClientIP, User, Category, Reason | Format-Table -AutoSize -Wrap

    Write-Host "`n--- Detail per record (Evidence = raw fields from the log, NativeMessage = unmodified original text) ---" -ForegroundColor Cyan
    $all | ForEach-Object {
        Write-Host "[$($_.Time)] $($_.Source) | $($_.User) @ $($_.ClientIP)" -ForegroundColor White
        Write-Host "    Evidence:      $($_.Evidence)" -ForegroundColor Gray
        Write-Host "    Guidance:      $($_.Guidance)" -ForegroundColor DarkGray
        Write-Host "    NativeMessage: $($_.NativeMessage)" -ForegroundColor DarkYellow
    }

    Write-Host "`n--- Summary by category ---" -ForegroundColor Cyan
    $all | Group-Object Category | Sort-Object Count -Descending |
        Select-Object Count, Name | Format-Table -AutoSize -Wrap

    if ($ExportCsv) {
        $all | Export-Csv -Path $CsvPath -NoTypeInformation -Encoding UTF8
        Write-Host "`nExported to: $CsvPath" -ForegroundColor Green
    }
}